# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nndALKtVanlwzr--F3MGJZYDQS_uoXAI
"""

import sys
import pandas as pd
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.utils import to_categorical
from tensorflow.keras.utils import plot_model
from PIL import Image
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import learning_curve
from tensorflow.keras.callbacks import History
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ReduceLROnPlateau

df = pd.read_csv('delhi_aqi.csv')

df = df.dropna()
df = df[(df != 0).all(1)]

df.to_csv('cleaned_dataset.csv', index=False)

def calculate_aqi_for_pollutant(concentration, pollutant):
    if pollutant == 'NO2':
        breakpoints = [0, 54, 101, 361, 650, 1250, 1650, 2049, 4000]
        AQI_values = [0, 50, 100, 200, 300, 400, 500]
    elif pollutant == 'SO2':
        breakpoints = [0, 36, 76, 186, 305, 605, 805, 1005, 5000]
        AQI_values = [0, 50, 100, 150, 200, 300, 400, 500]
    elif pollutant == 'O3':
        breakpoints = [0, 55, 71, 86, 106, 200, 405, 504]
        AQI_values = [0, 50, 100, 150, 200, 300, 400, 500]
    elif pollutant == 'PM2.5':
        breakpoints = [0, 12, 35.4, 55.4, 150.4, 250.4, 350.4, 500.4]
        AQI_values = [0, 50, 100, 150, 200, 300, 400, 500]
    else:
        raise ValueError("Invalid pollutant. Please choose 'NO2', 'CO', 'SO2', 'O3', or 'PM2.5'.")

    return calculate_aqi(concentration, breakpoints, AQI_values)

def calculate_aqi(concentration, breakpoints, AQI_values):
    for i in range(len(breakpoints) - 1):
        if breakpoints[i] <= concentration <= breakpoints[i + 1]:
            conc_low = breakpoints[i]
            conc_high = breakpoints[i + 1]
            aqi_low = AQI_values[i]
            aqi_high = AQI_values[i + 1]
            aqi = ((aqi_high - aqi_low) / (conc_high - conc_low)) * (concentration - conc_low) + aqi_low
            return aqi
    return None

df.drop(columns=['co'], inplace=True)
df['pm2_5'] = ((df['pm2_5'] - df['pm2_5'].min()) / (df['pm2_5'].max() - df['pm2_5'].min())) * 500
df['pm2_5'] = df['pm2_5'].apply(lambda x: min(x, 500))
df.to_csv('updatedAQI.csv', index=False)

df['AQI_no2'] = df['no2'].apply(lambda x: calculate_aqi_for_pollutant(x, 'NO2'))
df['AQI_so2'] = df['so2'].apply(lambda x: calculate_aqi_for_pollutant(x, 'SO2'))
df['AQI_o3'] = df['o3'].apply(lambda x: calculate_aqi_for_pollutant(x, 'O3'))
df['AQI_pm2_5'] = df['pm2_5'].apply(lambda x: calculate_aqi_for_pollutant(x, 'PM2.5'))

df.to_csv('updatedAQI.csv', index=False)

def health_issues_and_remedies_for_pollutant_aqi(pollutant, aqi):
    if pollutant == 'NO2':
        if aqi >= 0 and aqi <= 50:
            issue = "Minor respiratory irritation(NO2)"
            remedies = "Spend more time indoors in well-ventilated areas, avoid strenuous outdoor activities."
        elif aqi >= 51 and aqi <= 100:
            issue = "Increased respiratory symptoms in sensitive individuals(NO2)"
            remedies = "Limit outdoor activities, use air purifiers indoors."
        elif aqi >= 101 and aqi <= 150:
            issue = "Aggravation of respiratory conditions (asthma, bronchitis)(NO2)"
            remedies = "Stay indoors, use air purifiers with HEPA filters, consider wearing masks."
        else:
            issue = "Severe respiratory distress(NO2)"
            remedies = "Remain indoors with air purifiers, seek medical attention if symptoms worsen."
    elif pollutant == 'pm2_5':
        if aqi >= 0 and aqi <= 100:
            issue = "Minor headaches(pm2_5)"
            remedies = "Ventilate indoor spaces, reduce sources of CO (e.g., gas appliances)."
        elif aqi >= 100 and aqi <= 200:
            issue = "Headaches, dizziness(pm2_5)"
            remedies = "Increase ventilation, avoid using gas stoves without proper exhaust."
        elif aqi >= 200 and aqi <= 250:
            issue = "Nausea, fatigue(pm2_5)"
            remedies = "Immediately ventilate area, seek fresh air, and avoid further exposure."
        else:
            issue = "Severe symptoms (unconsciousness, death)(pm2_5)"
            remedies = "Evacuate to fresh air, seek medical attention immediately."
    elif pollutant == 'SO2':
        if aqi >= 0 and aqi <= 50:
            issue = "Minor respiratory irritation(SO2)"
            remedies = "Limit outdoor activities, use air purifiers indoors."
        elif aqi >= 51 and aqi <= 100:
            issue = "Increased respiratory symptoms in sensitive individuals(SO2)"
            remedies = "Avoid strenuous outdoor activities, use air purifiers indoors."
        elif aqi >= 101 and aqi <= 150:
            issue = "Aggravation of respiratory conditions (asthma, bronchitis)(SO2)"
            remedies = "Stay indoors, use air purifiers with HEPA filters, consider wearing masks."
        else:
            issue = "Severe respiratory distress(SO2)"
            remedies = "Remain indoors with air purifiers, seek medical attention if symptoms worsen."
    elif pollutant == 'O3':
        if aqi >= 0 and aqi <= 50:
            issue = "Minor respiratory irritation(O3)"
            remedies = "Limit outdoor activities, use air purifiers indoors."
        elif aqi >= 51 and aqi <= 100:
            issue = "Increased respiratory symptoms in sensitive individuals(O3)"
            remedies = "Avoid strenuous outdoor activities, use air purifiers indoors."
        elif aqi >= 101 and aqi <= 150:
            issue = "Aggravation of respiratory conditions (asthma, bronchitis)(O3)"
            remedies = "Stay indoors, use air purifiers with HEPA filters, consider wearing masks."
        else:
            issue = "Severe respiratory distress(O3)"
            remedies = "Remain indoors with air purifiers, seek medical attention if symptoms worsen."
    else:
        issue = "Invalid pollutant"
        remedies = "N/A"

    return issue, remedies

no2=df['AQI_no2']
so2=df['AQI_so2']
pm2_5=df['AQI_pm2_5']
o3=df['AQI_o3']
AQI=[]
issues=[]
remedies=[]
for i in range(len(df)):
    no2= df['AQI_no2'].iloc[i]
    so2=df['AQI_so2'].iloc[i]
    pm2_5=df['AQI_pm2_5'].iloc[i]
    o3=df['AQI_o3'].iloc[i]
    maxv = max(no2, so2, pm2_5,o3)
    AQI.append(maxv)
    if maxv == no2:
        pollutant = "NO2"
    elif maxv == so2:
        pollutant = "SO2"
    elif maxv == pm2_5:
        pollutant = "pm2_5"
    else:
        pollutant = "O3"
    [issue,remedy]=health_issues_and_remedies_for_pollutant_aqi(pollutant,maxv)
    issues.append(issue)
    remedies.append(remedy)
df['issues']=issues
df['remedies']=remedies
df['AQI']=AQI
df.to_csv('updatedAQI.csv', index=False)

df.dropna(inplace=True)
X = df[['AQI_no2', 'AQI_so2', 'AQI_o3','AQI_pm2_5']].astype(float)
y = df['AQI'].astype(float)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""# **Random Forest**"""

X_train_rf = X_train.values.reshape(X_train.shape[0], -1)
X_test_rf = X_test.values.reshape(X_test.shape[0], -1)

rf_model = RandomForestRegressor(max_depth=10, min_samples_leaf=5, n_estimators=100)

rf_model.fit(X_train_rf, y_train)

rf_predictions = rf_model.predict(X_test_rf)

# Example of receiving input from Node.js and sending output back
# Example of receiving input from Node.js and sending output back
if __name__ == "__main__":
    # Example input received from Node.js
    no2 = float(sys.argv[1])
    so2 = float(sys.argv[2])
    o3 = float(sys.argv[3])
    pm2_5 = float(sys.argv[4])

    # Reshape input data for prediction
    input_data = np.array([[no2, so2, o3, pm2_5]])

    # Make predictions
    result = rf_model.predict(input_data)

    print(result)  # This would typically be sent back to Node.js for further processing
